---
- name: fzf-tab
  hosts: localhost
  tasks:
    - name: Clone
      ansible.builtin.git:
        repo: 'https://github.com/Aloxaf/fzf-tab.git'
        dest: "{{ [distfiles_dir, 'fzf-tab'] | path_join }}"
        single_branch: true
        version: fac145167f7ec1861233c54de0c8900b09c650fe

    - name: Create root directory
      ansible.builtin.file:
        path: "{{ ['/', 'usr', 'share', 'zsh', 'plugins', 'fzf-tab'] | path_join }}"
        state: directory
      become: true

    - name: Install lib
      ansible.builtin.copy:
        src: "{{ [distfiles_dir, 'fzf-tab', 'lib'] | path_join }}"
        dest: "{{ ['/', 'usr', 'share', 'zsh', 'plugins', 'fzf-tab'] | path_join }}"
      become: true

    - name: Install script
      ansible.builtin.copy:
        src: "{{ [distfiles_dir, 'fzf-tab', 'fzf-tab.zsh'] | path_join }}"
        dest: "{{ ['/', 'usr', 'share', 'zsh', 'plugins', 'fzf-tab'] | path_join }}"
      become: true
