---
- name: glow
  hosts: localhost
  tasks:
    - name: Clone
      ansible.builtin.git:
        repo: 'https://github.com/charmbracelet/glow.git'
        dest: "{{ [distfiles_dir, 'glow'] | path_join }}"
        single_branch: true
        version: ba37804fd57d82fdea1e2a4275884a76f27c1d8f

    - name: Build
      ansible.builtin.command:
        cmd: go build
        creates: "{{ [distfiles_dir, 'glow', 'glow'] | path_join }}"
        chdir: "{{ [distfiles_dir, 'glow'] | path_join }}"

    - name: Create root directories
      ansible.builtin.file:
        path: "{{ ['/', 'usr', 'local', 'bin'] | path_join }}"
        state: directory
      become: true

    - name: Install
      ansible.builtin.copy:
        src: "{{ [distfiles_dir, 'glow', 'glow'] | path_join }}"
        dest: "{{ ['/', 'usr', 'local', 'bin'] | path_join }}"
        mode: 'u=rwx,g=rx,o=rx'
      become: true

    - name: Cleanup
      ansible.builtin.file:
        path: "{{ [distfiles_dir, 'glow', 'glow'] | path_join }}"
        state: absent
