---
- name: neovim
  hosts: localhost
  tasks:
    - name: Clone
      ansible.builtin.git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: "{{ [distfiles_dir, 'neovim'] | path_join }}"
        force: true
        single_branch: true
        version: 99e8b613760820199faac8ca101c5becd4b2374f

    - name: Make
      community.general.make:
        chdir: "{{ [distfiles_dir, 'neovim'] | path_join }}"
        params:
          CMAKE_BUILD_TYPE: RelWithDebInfo

    - name: Install
      community.general.make:
        chdir: "{{ [distfiles_dir, 'neovim'] | path_join }}"
        target: install
      become: true
