---
- name: neovim
  hosts: localhost
  tasks:
    - name: Clone
      ansible.builtin.git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: "{{ [distfiles_dir, 'neovim'] | path_join }}"
        force: true
        single_branch: true
        version: 2605ce937735f99d15ee8e3ee38cc33ebffa78ca

    - name: Make
      community.general.make:
        chdir: "{{ [distfiles_dir, 'neovim'] | path_join }}"
        params:
          CMAKE_BUILD_TYPE: RelWithDebInfo

    - name: Install
      community.general.make:
        chdir: "{{ [distfiles_dir, 'neovim'] | path_join }}"
        target: install
      become: true
