---
- name: neovim
  hosts: localhost
  tasks:
    - name: Clone
      ansible.builtin.git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: "{{ [distfiles_dir, 'neovim'] | path_join }}"
        force: true
        single_branch: true
        version: 4f97239661ebf569fa701f211dd92ef1919bc922

    - name: Make
      community.general.make:
        chdir: "{{ [distfiles_dir, 'neovim'] | path_join }}"
        params:
          CMAKE_BUILD_TYPE: Release

    - name: Install
      community.general.make:
        chdir: "{{ [distfiles_dir, 'neovim'] | path_join }}"
        target: install
      become: true
