---
- name: ripgrep
  hosts: localhost
  roles:
    - role: cargo
      vars:
        url: 'https://github.com/BurntSushi/ripgrep.git'
        repo_dir: ripgrep
        version: 57c190d56eedac90c061a238b63dbfed434fee50
        package_name: ripgrep
        build_root: []
