---
- name: starship
  hosts: localhost
  tasks:
    - name: Clone
      ansible.builtin.git:
        repo: 'https://github.com/starship/starship.git'
        dest: "{{ [distfiles_dir, 'starship'] | path_join }}"
        single_branch: true
        version: b4d401c3044edbc3e80b532c0843ad30bfe82400

    - name: Install
      ansible.builtin.command:
        cmd: ./install/install.sh --yes
        chdir: "{{ [distfiles_dir, 'starship'] | path_join }}"
      become: true
