---
- name: zsh-completions
  hosts: localhost
  tasks:
    - name: Clone
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-completions.git'
        dest: "{{ [distfiles_dir, 'zsh-completions'] | path_join }}"
        single_branch: true
        version: 46317b36e287341176b47f97a707abcf10ade8b4

    - name: Create root directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ ['/', 'usr', 'share', 'zsh', 'site-functions'] | path_join }}"
        - "{{ ['/', 'usr', 'share', 'doc', 'zsh-completions'] | path_join }}"
      become: true

    - name: Copy sources
      ansible.builtin.copy:
        src: "{{ [distfiles_dir, 'zsh-completions', 'src'] | path_join }}/"
        dest: "{{ ['/', 'usr', 'share', 'zsh', 'site-functions'] | path_join }}"
        mode: 'u=rw,g=r,o=r'
      become: true

    - name: Copy manual
      ansible.builtin.copy:
        src: "{{ [distfiles_dir, 'zsh-completions', 'README.md'] | path_join }}"
        dest: "{{ ['/', 'usr', 'share', 'doc', 'zsh-completions'] | path_join }}"
        mode: 'u=rw,g=r,o=r'
      become: true
